import json
class PromptBuilder:
    @staticmethod
    def planner_system_prompt():

        return """
            You are an expert Senior Data Scientist.

            Your job is to understand a dataset ONLY from its metadata.

            Infer:

            1. Dataset Type
            2. Business Domain
            3. Possible Target Variable
            4. Business Metrics
            5. Business Dimensions
            6. Identifier Columns
            7. Recommended Analyses

            Rules

            - Never hallucinate.
            - Never invent columns.
            - Use only supplied metadata.
            - Return ONLY valid JSON.
            """

    @staticmethod
    def planner_prompt(dataset_profile, column_profiles):

        return f"""
DATASET PROFILE

Rows : {dataset_profile.rows}

Columns : {dataset_profile.columns}

Missing Cells : {dataset_profile.missing_percentage}

Duplicate Rows : {dataset_profile.duplicate_rows}


COLUMN INFORMATION

{json.dumps(column_profiles, indent=2)}


Return ONLY valid JSON.

Schema

{{
    "dataset_type":"",
    "business_domain":"",
    "possible_target":null,
    "metrics":[],
    "dimensions":[],
    "identifiers":[],
    "recommended_analyses":[
        {{
            "analysis":"",
            "priority":1,
            "confidence":1.0,
            "reason":""
        }}
    ],
    "summary":""
}}

Rules

- Infer business metrics.
- Infer business dimensions.
- Detect identifier columns.
- Recommend analyses in execution order.
- Return ONLY JSON.
"""

    # =====================================================
    # Insight Agent
    # =====================================================

    @staticmethod
    def insight_system_prompt():

        return """
You are a Principal Data Scientist.

You are analysing structured evidence generated by an
automated EDA system.

Never compute statistics.

Never hallucinate.

Never invent dataset columns.

Reason ONLY from supplied evidence.

Return ONLY valid JSON.
"""

    @staticmethod
    def insight_prompt(report, evidence):

        planner = report.get("planner", {})
        profile = report.get("dataset_profile")

        return f"""
DATASET PROFILE

Rows : {profile.rows}

Columns : {profile.columns}

Dataset Type : {planner.get("dataset_type","Unknown")}

Business Domain : {planner.get("business_domain","Unknown")}

Possible Target : {planner.get("possible_target","Unknown")}

Business Metrics

{planner.get("metrics", [])}

Business Dimensions

{planner.get("dimensions", [])}


=========================================================
ANALYSIS SUMMARY
=========================================================

Overview

{report["overview"].summary}

----------------------------------------

Data Quality

{report["data_quality"].summary}

----------------------------------------

Numerical

{report["numerical"].summary}

----------------------------------------

Categorical

{report["categorical"].summary}

----------------------------------------

Correlation

{report["correlation"].summary}

----------------------------------------

Relationships

{report["relationships"].summary}


=========================================================
STRUCTURED EVIDENCE
=========================================================

Total Evidence Objects : {len(evidence)}

{json.dumps(evidence, indent=2)}

=========================================================
YOUR TASK
=========================================================

Generate VALID JSON.

Schema

{{
    "executive_summary":"",
    "key_findings":[],
    "business_recommendations":[],
    "data_quality_risks":[],
    "ml_readiness":"",
    "feature_engineering":[],
    "next_steps":[]
}}

Rules

1. Use ONLY supplied evidence.
2. Never invent columns.
3. Never fabricate statistics.
4. Explain findings in business language.
5. Mention business risks.
6. Mention ML readiness.
7. Suggest feature engineering.
8. Suggest next analytical steps.

Return ONLY JSON.
"""

    # =====================================================
    # Chat Agent (Future)
    # =====================================================

    @staticmethod
    def chat_system_prompt():

        return """
You are an AI Data Science Assistant.

Answer user questions ONLY from supplied analytical
context.

Never hallucinate.

If information is unavailable, say so.
"""

    @staticmethod
    def chat_prompt(question, context):

        return f"""
Dataset Context

{context}

Question

{question}

Answer using ONLY the supplied context.
"""